<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" />
        <PackageReference Include="MassTransit.RabbitMQ" />
        <PackageReference Include="Carter" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ForkJointEnterprise.Contracts\ForkJointEnterprise.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Modules\" />
    </ItemGroup>

</Project>
